server:
  port: 8888 # 服务端口

eureka:
  instance: 
    hostname: peer1
  client:
    registerWithEureka: true # 是否向 Eureka 注册服务。该应用为服务注册中心，不需要自注册，设置为 false
    fetchRegistry: true      # 是否检索服务。该应用为服务注册中心，职责为注册和发现服务，无需检索服务，设置为 false
    serviceUrl: 
      defaultZone: http://peer2:8889/eureka/
      